---
name: Test matrix -- include etc.

on:
  push:
    branches: [ "main" ]

jobs:

  simple:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [os-1, os-2]
        pyversion: [pyv-1, pyv-2]

    steps:
    - name: Info
      run: |
        echo "matrix.os = ${{ matrix.os }}"
        echo "matrix.pyversion = ${{ matrix.pyversion }}"

  incl_add:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [os-1, os-2]
        pyversion: [pyv-1, pyv-2]
        full: [true]
        include:
        - os: os-1
          pyversion: pyv-3

    steps:
    - name: Info
      run: |
        echo "matrix.os = ${{ matrix.os }}"
        echo "matrix.pyversion = ${{ matrix.pyversion }}"
        echo "matrix.full = ${{ matrix.full }}"

  incl_new:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [os-1, os-2]
        pyversion: [pyv-1, pyv-2]
        include:
        - os: os-1
          test: test-1

    steps:
    - name: Info
      run: |
        echo "matrix.os = ${{ matrix.os }}"
        echo "matrix.pyversion = ${{ matrix.pyversion }}"
        echo "matrix.test = ${{ matrix.test }}"

  exclude:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [os-1, os-2]
        pyversion: [pyv-1, pyv-2]
        exclude:
        - os: os-1
          pyversion: pyv-2

    steps:
    - name: Info
      run: |
        echo "matrix.os = ${{ matrix.os }}"
        echo "matrix.pyversion = ${{ matrix.pyversion }}"
