---
name: Test matrix -- include etc.

on:
  push:
    branches: [ "main" ]

jobs:

  simple_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windwows-latest]
        python-version: ['3.9', '3.12']

    steps:
    - name: Info
      run: |
        echo "matrix.os = ${{ matrix.os }}"
        echo "matrix.python-version = ${{ matrix.python-version }}"

  include_add_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windwows-latest]
        python-version: ['3.9', '3.12']
        include:
        - os: ubuntu-latest
          python-version: '3.8'

    steps:
    - name: Info
      run: |
        echo "matrix.os = ${{ matrix.os }}"
        echo "matrix.python-version = ${{ matrix.python-version }}"

  include_new_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windwows-latest]
        python-version: ['3.9', '3.12']
        include:
        - os: ubuntu-latest
          test: 'hello'

    steps:
    - name: Info
      run: |
        echo "matrix.os = ${{ matrix.os }}"
        echo "matrix.python-version = ${{ matrix.python-version }}"
        echo "matrix.test = ${{ matrix.test }}"

  exclude_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windwows-latest]
        python-version: ['3.9', '3.12']
        exclude:
        - os: ubuntu-latest
          python-version: '3.12'

    steps:
    - name: Info
      run: |
        echo "matrix.os = ${{ matrix.os }}"
        echo "matrix.python-version = ${{ matrix.python-version }}"
